name: hacs
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/action@d556e736723344f83838d08488c983a15381059a  # 22.5.0
        with:
          category: integration
          comment: false
